web:
  build: .
  container_name: hipay-tpp-prestashop
  ports:
    - "80:80"
  environment:
    PS_DOMAIN: localhost
    ADMIN_MAIL: demo@hipay.com
    ADMIN_PASSWD: hipay123
    PS_LANGUAGE: en
    PS_COUNTRY: gb
    PS_INSTALL_AUTO: 1
    PS_DEV_MODE: 1
    PS_FOLDER_ADMIN: admin-hipay
    PS_FOLDER_INSTALL: installOLD