prestashop:
  container_name: hipay-enterprise-shop-ps16
  build: .
  links:
    - smtp
    - mysql
mysql:
  container_name: mysql-hipay-enterprise
  image: mysql:5.6.23
smtp:
  image: schickling/mailcatcher
  container_name: smtp-hipay-enterprise