prestashop:
  container_name: hipay-fullservice-shop-ps16
  build: .
  links:
    - smtp
    - mysql
mysql:
  container_name: mysql-hipay-fullservice
  image: mysql:5.6.23
smtp:
  image: schickling/mailcatcher
  container_name: smtp-hipay-fullservice